apiVersion: batch/v1
kind: Job
metadata:
  name: crawl
spec:
  # adjust for parallelism
  parallelism: 50
  backoffLimit: 10000 # to avoid crawls failing due to sporadic socket-induced crashes
  template:
    metadata:
      name: openwpm-crawl
    spec:
      containers:
      - name: openwpm-crawl
        image: docker.io/openwpm/openwpm:commit-d5b8b72120a20ab566c3e25165f9efa4edfef67f
        command: ["python"]
        args: ["crawler.py"]
        env:
        - name: AWS_ACCESS_KEY_ID
          valueFrom:
            secretKeyRef:
              name: aws-config
              key: aws_access_key_id
        - name: AWS_SECRET_ACCESS_KEY
          valueFrom:
            secretKeyRef:
              name: aws-config
              key: aws_secret_access_key
        - name: NUM_BROWSERS
          value: '1'
        - name: REDIS_HOST
          value: '10.0.0.3'
        - name: REDIS_QUEUE_NAME
          value: 'crawl-queue'
        - name: CRAWL_DIRECTORY
          value: '2019_08_15_webcompat_crawl_test_1'
        - name: S3_BUCKET
          value: 'openwpm-crawls'
        - name: HTTP_INSTRUMENT
          value: '1'
        - name: COOKIE_INSTRUMENT
          value: '1'
        - name: NAVIGATION_INSTRUMENT
          value: '1'
        - name: JS_INSTRUMENT
          value: '1'
        - name: JS_INSTRUMENT_MODULES
          value: 'webcompat'
        - name: SAVE_CONTENT
          value: 'script,stylesheet,main_frame,sub_frame'
        - name: DWELL_TIME
          value: '10'
        - name: TIMEOUT
          value: '60'
        - name: SENTRY_DSN
          valueFrom:
            secretKeyRef:
              name: sentry-config
              key: sentry_dsn
        resources:
          # these are taken at face value by the autoscaler, so they should match actual
          # resources required by any single instance/container as good as possible
          # see: https://cloud.google.com/kubernetes-engine/docs/concepts/cluster-autoscaler
          # tip: observe `kubectl top nodes` during auto-scaled crawls to get an idea of how
          # resources are being utilized
          requests:
            cpu: 750m
          limits:
            cpu: 1
      restartPolicy: OnFailure
